### PR TITLE
Index Autoconfiguration, overcoming filedescriptor limitations

### LINKED ISSUE #60: index can crash if running out of file handles
With the default number of file handles (1024) on an ubuntu 16.04 the indexer can crash caused by a corrupted file.

This seems to originate from an unhandled problem on a filestream somewhere in the value store/memory map manager. The error gets ignored, the output file gets corrupted and the indexer crashes shortly after  trying to read the file.

Increasing the number of file handles workarounds the problem.

A fix should

- improve error handling, properly detect if we run out of file handles
- throttle indexer to avoid problems if file handles get short
- proper error messages

### PR DESCRIPTION
**Pull request by hendrikmuhs**
This change implements auto-configuration of index settings, including configuring the maximum number of segments which is directly connected to the number of file descriptors. If not externally given it tries to increase the limit (usually from 1024 to 1M). In case of running low on file descriptors index operations are automatically throttled so that concurrent compaction can catch up and reduce open descriptors.

Also changes the queue implementation - after benchmarking - to use condition variables instead of a spin-lock if the queue runs full or empty. This improves indexing performance and also fixes a problem in the spin-lock implementation that could cause cpu hogging. 

fixes #60

### CODE REVIEW

File: keyvi/include/keyvi/index/constants.h [hunk 1]
```diff
@@ -25,9 +25,25 @@
...
+static const char INDEX_MAX_SEGMENTS[] = "max_segments";
+static const char SEGMENT_COMPILE_KEY_THRESHOLD[] = "segment_compile_key_threshold";
+static const char MAX_CONCURRENT_MERGES[] = "max_concurrent_merges";
+
+// defaults
+static const size_t DEFAULT_REFRESH_INTERVAL = 1000ul;
+static const size_t DEFAULT_COMPILE_KEY_THRESHOLD = 10000ul;
+static const char DEFAULT_KEYVIMERGER_BIN[] = "keyvimerger";
+
+// spinlock wait time if there are to many segments
```
Comment (amit-cliqz) [inline keyvi/include/keyvi/index/constants.h]: typo: to --> too

File: keyvi/include/keyvi/index/internal/index_auto_config.h [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+namespace keyvi {
+namespace index {
+namespace internal {
+
+class IndexAutoConfig final {
+ public:
+  static size_t MaxSegments() {
+    // increase file descriptors and leave some extra room, to be improved later
+    size_t file_descriptors = keyvi::util::OsUtils::TryIncreaseFileDescriptors();
+    return file_descriptors - 100;
```
Comment (amit-cliqz) [inline keyvi/include/keyvi/index/internal/index_auto_config.h]: Magic number 100: As I understand, you don't want to use all the file descriptors. Can you please explain why did you choose 100?

File: keyvi/include/keyvi/index/internal/index_writer_worker.h [hunk 3]
```diff
@@ -209,6 +211,20 @@ class IndexWriterWorker final {
   merge_policy_t merge_policy_;
   util::ActiveObject<IndexPayload> compiler_active_object_;
 
+  void CompileIfThresholdIsHit() {
+    if (++payload_.write_counter_ > payload_.compile_key_threshold_) {
+      compiler_active_object_([](IndexPayload& payload) { Compile(&payload); });
+      payload_.write_counter_ = 0;
+
+      // worst case scenario, to many segments, throttle further writes until we are below the limit
```
Comment (amit-cliqz) [inline keyvi/include/keyvi/index/internal/index_writer_worker.h]: typo: to --> too

File: keyvi/include/keyvi/index/internal/index_auto_config.h (hunk 2 above)
Comment (hendrikmuhs) [reply keyvi/include/keyvi/index/internal/index_auto_config.h]: I agree, thats extremely vague. The problem is basically that I want to leave some room between the total limit and the setting, so that the client can have some open descriptors as well, e.g. because you create the index from a reading a open file. The other reason: compiling requires 2 open descriptors, so I need some room for that as well.

I think there is no perfect answer. I will improve the documentation. On the other side: Incrementing the file descriptors already helps, on Linux it's upped from 1024 (easy to hit) to 1 million, hitting 1 million segments == file descriptors is quite unlikely.

Comment (amit-cliqz) [reply keyvi/include/keyvi/index/internal/index_auto_config.h]: Thanks for the answer, it's clear now.

File: keyvi/include/keyvi/index/internal/index_writer_worker.h [hunk 4]
```diff
@@ -85,7 +90,11 @@ class IndexWriterWorker final {
     boost::filesystem::path index_toc_file_part_;
     internal::IndexSettings settings_;
     std::list<MergeJob> merge_jobs_;
-    size_t max_concurrent_merges_ = 2;
+    size_t max_concurrent_merges_;
+    size_t max_segments_;
+    size_t compile_key_threshold_;
+    size_t index_refresh_interval_;
```
Comment (narekgharibyan) [inline keyvi/include/keyvi/index/internal/index_writer_worker.h]: Looks like these members are only read after initialization, so we can have them `const` and initialize in constructor initializer list.

File: keyvi/tests/keyvi/util/single_producer_consumer_ringbuffer_test.cpp [hunk 5]
```diff
@@ -69,6 +72,7 @@ BOOST_AUTO_TEST_CASE(SimpleTest) {
 
 BOOST_AUTO_TEST_CASE(SizeTest) {
   SingeProducerSingleConsumerRingBuffer<Item, 11> s;
+  auto now = std::chrono::system_clock::now();
```
Comment (narekgharibyan) [inline keyvi/tests/keyvi/util/single_producer_consumer_ringbuffer_test.cpp]: Looks this var is unused.

File: keyvi/include/keyvi/util/os_utils.h [hunk 6]
```diff
@@ -0,0 +1,60 @@
...
+    struct rlimit limit;
+
+    getrlimit(RLIMIT_NOFILE, &limit);
+    if (limit.rlim_cur != limit.rlim_max) {
+      // try different limits, as platforms behave differently
+      std::vector<size_t> limits{limit.rlim_max, 10000ul, 3200, 1024};
+
+      for (size_t l : limits) {
+        limit.rlim_cur = l;
+        if (setrlimit(RLIMIT_NOFILE, &limit) == 0) {
```
[the remark this answers is not in the document]
Comment (hendrikmuhs) [reply keyvi/include/keyvi/util/os_utils.h]: I am re-reading the limit now, that seems to me the most simplest and safest solution, because - as I read - setting the limits might be flaky on some platforms.
