### PR TITLE
check stream for WriteToFile

### LINKED ISSUE #224: No errors from `WriteToFile` when output path contains non existent folder
**Describe the bug**
When you call `WriteToFile` and specify output path with folder that doesn't exists, `WriteToFile` silently do nothing

**To Reproduce**
```python
import os
import keyvi.compiler


c = keyvi.compiler.JsonDictionaryCompiler()
c.Add(b'1', b'123')
c.Compile()

output_path = '/tmp/thispathdoesntexists/test.kv'
c.WriteToFile(output_path)

assert os.path.exists(output_path)  # will fail, because file doesn't exists
```

**Expected behavior**

Exception on `WriteToFile`

### PR DESCRIPTION
**Pull request by hendrikmuhs**
assert broken stream

fixes #224

### CODE REVIEW

File: keyvi/include/keyvi/dictionary/dictionary_compiler.h [hunk 1]
```diff
@@ -162,6 +162,11 @@ class DictionaryCompiler final {
     }
 
     std::ofstream out_stream(filename, std::ios::binary);
+
+    if (!out_stream.good()) {
+      throw std::invalid_argument("failed to open file");
```
Comment (narekgharibyan) [inline keyvi/include/keyvi/dictionary/dictionary_compiler.h:167]: Maybe we can include file-name in the message as well ? 
Also seems we are duplication the message in 4 places, prob we can have some either method or generic message to avoid duplication ?

**Review by narekgharibyan — COMMENTED** [review]
LGTM, but add 2 small suggestions.

File: keyvi/include/keyvi/util/os_utils.h [hunk 2]
```diff
@@ -64,6 +68,15 @@ class OsUtils {
     return limit.rlim_cur;
 #endif
   }
+
+  static inline std::ofstream OpenFileStream(const std::string& filename) {
```
Comment (narekgharibyan) [inline keyvi/include/keyvi/util/os_utils.h:72]: Maybe it's worth to add _out_ as part of function name to highlight it is opening an out file stream, like `OpenOutFileStream` ?

**Review by narekgharibyan — APPROVED** [review]
LGTM. 
@hendrikmuhs thanks for addressing suggestions.
